name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter pub get
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos --release
      - run: zip aws_parameter_store.app.zip "build/macos/Build/Products/Release/AWS Parameter Store.app"
      - uses: actions/upload-artifact@v1
        with:
          name: aws_parameter_store.app.zip
          path: aws_parameter_store.app.zip